CREATE TABLE Users (
    UserID SERIAL PRIMARY KEY,
    Username VARCHAR(255) UNIQUE NOT NULL,
    Password VARCHAR(255) NOT NULL
);

CREATE TABLE Projects (
    ProjectID SERIAL PRIMARY KEY,
    UserID INT,
    ProjectName VARCHAR(255) NOT NULL,
    FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
);

CREATE TABLE Tasks (
    TaskID SERIAL PRIMARY KEY,
    UserID INT,
    ProjectID INT,
    TaskName VARCHAR(255) NOT NULL,
    Deadline DATE NOT NULL,
    Completed BOOLEAN NOT NULL DEFAULT FALSE,
    ExpectedTime DECIMAL(10, 5) NOT NULL,
    FOREIGN KEY (ProjectID) REFERENCES Projects(ProjectID) ON DELETE CASCADE,
    FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
);
